"use client";

import Link from "next/link";
import { BookOpen, TrendingUp, Users, Zap, ArrowRight, ShieldCheck, Clock } from "lucide-react";
import { useAuth } from "@/context/AuthContext";

const ACADEMY_ARTICLES = [
  {
    slug: "saas-valuation-benchmarks-2026",
    title: "SaaS Valuation Benchmarks: What Institutional Investors Want in 2026",
    description: "Discover the exact MRR and LTV:CAC ratios that are currently closing Series A rounds in the Enterprise cohort.",
    category: "Valuation",
    time: "4 min read",
    author: "The FundabilityOS team",
    date: "updated 2 days ago"
  },
  {
    slug: "cac-payback-gap-mitigation",
    title: "The CAC Payback Gap: How to Fix Your Unit Economics Before Your Next Raise",
    description: "Identify the hidden pricing friction at Step 1.3.4 of your audit and learn how to mitigate it autonomously.",
    category: "Unit Economics",
    time: "6 min read",
    author: "The FundabilityOS team",
    date: "updated 5 days ago"
  },
  {
    slug: "investor-matching-algorithms",
    title: "Beyond the Warm Intro: Using Matching Algorithms to Scale Your Capital Hunt",
    description: "Why warm intros are becoming a bottleneck and how to use data-driven matching to find your lead investor.",
    category: "Fundraising",
    time: "5 min read",
    author: "The FundabilityOS team",
    date: "updated 1 week ago"
  }
];

export default function AcademyPage() {
  const { user } = useAuth();
  
  return (
    <div className="bg-[#fcfcfc] min-h-screen">
      {/* Navigation Header Stub - Only show for public visitors or when no layout is active */}
      {!user && (
      <nav className="border-b border-gray-100 bg-white sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center gap-2 group">
            <div className="w-8 h-8 bg-[#022f42] rounded-sm flex items-center justify-center transform rotate-3 group-hover:rotate-0 transition-transform shadow-md">
              <Zap className="w-4 h-4 text-[#ffd800]" />
            </div>
            <span className="font-black text-xl text-[#022f42] uppercase tracking-tighter">Fundability<span className="text-[#ffd800]">OS</span></span>
          </Link>
          <div className="flex items-center gap-8">
            <Link href="/" className="text-sm font-bold text-gray-500 hover:text-[#022f42]">Main Site</Link>
            <Link href="/dashboard" className="bg-[#022f42] text-white px-6 py-2.5 text-xs font-black uppercase tracking-widest rounded-sm">Dashboard</Link>
          </div>
        </div>
      </nav>
      )}

      <div className="max-w-7xl mx-auto px-6 py-16">
        <div className="mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#ffd800] text-[#022f42] text-[10px] font-black uppercase tracking-widest mb-6 rounded-sm shadow-sm">
            <BookOpen className="w-3 h-3" /> Alpha Insights Hub
          </div>
          <h1 className="text-6xl font-black text-[#022f42] tracking-tighter leading-none mb-6">
            Institutional investor <br />
            <span className="text-gray-300 italic">intelligence</span> for founders.
          </h1>
          <p className="text-xl text-gray-500 max-w-2xl font-medium leading-relaxed">
            Free, bite-sized strategies generated by FundabilityOS&apos;s autonomous revenue engine. 
            No gatekeeing. Just pure data for your next round.
          </p>
        </div>

        {/* Featured Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
          <div className="lg:col-span-2">
            <div className="space-y-12">
              {ACADEMY_ARTICLES.map((article) => (
                <Link 
                  key={article.slug} 
                  href={`/academy/${article.slug}`}
                  className="group block bg-white p-8 border border-gray-100 rounded-sm hover:border-[#ffd800] transition-all hover:shadow-2xl hover:shadow-[#ffd800]/5"
                >
                  <div className="flex flex-col md:flex-row gap-8">
                    <div className="flex-1">
                      <div className="flex items-center gap-4 mb-4">
                        <span className="text-[10px] font-black uppercase tracking-widest text-[#90cdf4]">{article.category}</span>
                        <div className="flex items-center gap-1.5 text-gray-400 text-[10px] font-bold">
                          <Clock className="w-3 h-3" /> {article.time}
                        </div>
                      </div>
                      <h2 className="text-3xl font-black text-[#022f42] leading-tight mb-4 group-hover:text-[#1b4f68] transition-colors">
                        {article.title}
                      </h2>
                      <p className="text-gray-500 font-medium mb-6 line-clamp-2 leading-relaxed">
                        {article.description}
                      </p>
                      <div className="flex items-center justify-between mt-auto">
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 bg-gray-100 rounded-full flex items-center justify-center border border-gray-200">
                            <Users className="w-3 h-3 text-gray-400" />
                          </div>
                          <span className="text-[10px] font-black text-[#022f42] uppercase tracking-wider">{article.author}</span>
                        </div>
                        <div className="flex items-center gap-1 text-[#022f42] font-black text-xs uppercase tracking-widest group-hover:translate-x-2 transition-transform">
                          Read Full Insight <ArrowRight className="w-4 h-4" />
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>

          {/* Sidebar CTA */}
          <div className="lg:col-span-1">
            <div className="sticky top-32 space-y-8">
              <div className="bg-[#022f42] p-8 rounded-sm text-white shadow-2xl shadow-[#022f42]/40 relative overflow-hidden">
                <div className="absolute -right-4 -bottom-4 w-32 h-32 bg-white/5 rounded-full blur-3xl" />
                <TrendingUp className="w-10 h-10 text-[#ffd800] mb-6" />
                <h3 className="text-2xl font-black uppercase tracking-tight mb-4 leading-none">Calculate Your <br />Raise Velocity</h3>
                <p className="text-sm text-[#90cdf4] font-medium mb-8 leading-relaxed">
                  Run the institutional audit to see how your metrics compare to the benchmarks in these articles.
                </p>
                <Link 
                  href="/dashboard" 
                  className="block w-full bg-[#ffd800] text-[#022f42] text-center py-4 text-xs font-black uppercase tracking-widest rounded-sm hover:scale-[1.02] transition-transform shadow-xl shadow-[#ffd800]/20"
                >
                  Launch Free Audit
                </Link>
              </div>

              <div className="border border-gray-100 bg-white p-8 rounded-sm">
                <h4 className="text-sm font-black text-[#022f42] uppercase tracking-widest mb-6 border-b border-gray-50 pb-4 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-500" /> Weekly Alpha Digest
                </h4>
                <p className="text-xs text-gray-500 font-bold mb-6 italic leading-relaxed">
                  "The CAC:LTV ratio for 2026 is tightening. Most seed rounds now require a &gt;3.5x ratio to clear lead VC committees."
                </p>
                <div className="space-y-4">
                  <input 
                    type="email" 
                    placeholder="Enter your email" 
                    className="w-full bg-gray-50 border border-gray-100 p-3 text-xs rounded-sm focus:outline-none focus:border-[#022f42] transition-colors"
                  />
                  <button className="w-full bg-[#022f42] text-white py-3 text-[10px] font-black uppercase tracking-widest rounded-sm">
                    Join Audit List
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Modern Footer section - Only show for public visitors */}
      {!user && (
      <footer className="border-t border-gray-100 bg-white py-20 mt-20">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-12">
           <div className="flex items-center gap-2 group">
            <div className="w-8 h-8 bg-[#022f42] rounded-sm flex items-center justify-center shadow-lg">
              <Zap className="w-4 h-4 text-[#ffd800]" />
            </div>
            <span className="font-black text-xl text-[#022f42] uppercase tracking-tighter">Fundability<span className="text-[#ffd800]">OS</span> Academy</span>
          </div>
          <div className="flex gap-12 text-[10px] font-black uppercase tracking-widest text-gray-400">
            <Link href="/" className="hover:text-[#022f42] transition-colors">Main App</Link>
            <Link href="/privacy" className="hover:text-[#022f42] transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-[#022f42] transition-colors">Terms</Link>
          </div>
          <div className="text-[10px] font-bold text-gray-300">
            © 2026 Nextblaze / FundabilityOS Team. All rights reserved.
          </div>
        </div>
      </footer>
      )}
    </div>
  );
}
